const t = {
  uz: {
    home: "Bosh sahifa",
    about_us: "Biz haqimizda",
    projects: "Loyihalar",
    contact_us: "Bog'lanish",
    hero_title: "ApexBrat - Bizning loyihalarimiz bilan tanishing",
    hero_subtitle:
      "Innovatsion echimlar, yuqori sifat va muvaffaqiyatga intilish",
    hero_button: "Loyihalar bilan tanishish",
    about_description:
      "Bizning maqsadimiz - yuqori sifatli xizmatlar va innovatsion echimlar orqali mijozlarimizni qoniqtirish.",
    contact_message: "Bog'lanish uchun quyidagi formani to'ldiring.",
    login: "Kirish",
    username: "Foydalanuvchi nomi",
    password: "Parol",
    login_button: "Kirish",
    success: "Muvaffaqiyatli kirdingiz!",
    error: "Xato! Iltimos, ma'lumotlarni tekshiring.",
    registerSentences:
      "Agar shaxsiy akount yoq bolsa siz registiratsiya bo'lmiga o'tishingiz mumkun",
    signUp: "Ro'yhatdan o'tish",
    loginSentences:
      "Sizda allaqachon shaxsiy akaunt bolsa kirish qismiga o'ting",
    hero: `Innovatsiyalarni tadbiq etish orqali biznesingizni yangi bosqichga
      olib chiqing. Biz texnologik yechimlarimiz orqali muvaffaqiyatni
      ta'minlaymiz.`,
    contact: `Muloqot o‘rnatish uchun quyidagi formani to‘ldiring yoki bizga
    to‘g‘ridan-to‘g‘ri elektron pochta orqali murojaat qiling.`,
    first_name: "Ism",
    first_name_placeholder: "Ismingiz",
    last_name: "Familiya",
    last_name_placeholder: "Familiyangiz",
    email: "Email",
    email_placeholder: "Emailingiz",
    message: "Xabar",
    message_placeholder: "Xabaringizni bu yerda yozing...",
    send_message: "Xabarni yuborish",
    response_time: "Biz sizning xabaringizga 24 soat ichida javob beramiz.",
    about_intro:
      "Bizning kompaniyamiz mijozlarimizga texnologik yechimlar va xizmatlar bo‘yicha eng yaxshi tajribani taqdim etishga intiladi. Biz innovatsiyalar, yuqori sifat va hamkorlik asosida ishlashni maqsad qilganmiz.",
    about_us_alt: "Biz haqimizda",
    about_detail:
      "Bizning jamoamiz malakali mutaxassislar va strateglar bo‘lib, ular mijozlarimizga innovatsion loyihalar va muammolar yechimlarini taklif qiladi. Har bir loyiha - bu biz uchun yangi yutuq va imkoniyat.",
    service_1: "Innovatsion xizmatlar",
    service_2: "Yuqori sifatli texnologiyalar",
    service_3: "Mijozlarning ishonchi va mamnunligi",
    service: "Xizmatlar",
    branding: "Brending",
    design: "Dizayn",
    marketing: "Marketing",
    advertisement: "Reklama",
    company: "Kompaniya",
    about_us: "Biz haqimizda",
    contact: "Kontakt",
    jobs: "Ish o‘rinlari",
    press_kit: "Matbuot to‘plami",
    legal: "Huquqiy",
    terms_of_use: "Foydalanish shartlari",
    privacy_policy: "Maxfiylik siyosati",
    cookie_policy: "Cookie siyosati",
    company_info:
      "Apex Brat Solution. Ishonchli texnologiyalar taqdim etmoqda 2023-yildan beri",
  },
  ru: {
    home: "Главная",
    about_us: "О нас",
    projects: "Проекты",
    service: "Услуги",
    branding: "Брендинг",
    design: "Дизайн",
    marketing: "Маркетинг",
    advertisement: "Реклама",
    company: "Компания",
    about_us: "О нас",
    contact: "Контакт",
    jobs: "Работа",
    press_kit: "Пресс-кит",
    legal: "Правовая информация",
    terms_of_use: "Условия использования",
    privacy_policy: "Политика конфиденциальности",
    cookie_policy: "Политика использования cookies",
    company_info: "Apex Brat Solutuon. Надежные технологии с 2023 года",
    contact_us: "Свяжитесь с нами",
    hero_title: "ApexBrat - Знакомьтесь с нашими проектами",
    hero_subtitle:
      "Инновационные решения, высокое качество и стремление к успеху",
    hero_button: "Посмотреть проекты",
    about_description:
      "Наша цель - удовлетворить наших клиентов с помощью качественных услуг и инновационных решений.",
    contact_message: "Заполните форму ниже, чтобы связаться с нами.",
    login: "Войти",
    username: "Имя пользователя",
    password: "Пароль",
    login_button: "Войти",
    success: "Вы успешно вошли!",
    error: "Ошибка! Проверьте данные.",
    registerSentences:
      "Если у вас нет личного аккаунта, вы можете перейти на страницу регистрации.",
    signUp: "Регистрация",
    loginSentences:
      "Если у вас уже есть личная учетная запись, перейдите в раздел входа.",
    hero: "Внедряйте инновации и выведите ваш бизнес на новый уровень. Мы обеспечиваем успех с помощью наших технологических решений.",
    contact:
      "Для связи заполните следующую форму или свяжитесь с нами напрямую по электронной почте.",
    first_name: "Имя",
    first_name_placeholder: "Ваше имя",
    last_name: "Фамилия",
    last_name_placeholder: "Ваша фамилия",
    email: "Электронная почта",
    email_placeholder: "Ваш email",
    message: "Сообщение",
    message_placeholder: "Напишите ваше сообщение здесь...",
    send_message: "Отправить сообщение",
    response_time: "Мы ответим на ваше сообщение в течение 24 часов.",
    about_intro:
      "Наша компания стремится предоставить клиентам лучший опыт в области технологических решений и услуг. Мы нацелены на работу на основе инноваций, высокого качества и сотрудничества.",
    about_us_alt: "О нас",
    about_detail:
      "Наша команда состоит из квалифицированных специалистов и стратегов, которые предлагают клиентам инновационные проекты и решения. Каждый проект для нас - это новая победа и возможность.",
    service_1: "Инновационные услуги",
    service_2: "Высококачественные технологии",
    service_3: "Доверие и удовлетворенность клиентов",
  },
  en: {
    home: "Home",
    about_us: "About Us",
    projects: "Projects",
    contact_us: "Contact Us",
    hero_title: "ApexBrat - Explore Our Projects",
    hero_subtitle:
      "Innovative solutions, high quality, and a drive for success",
    hero_button: "Explore Projects",
    about_description:
      "Our mission is to satisfy our clients through high-quality services and innovative solutions.",
    contact_message: "Fill out the form below to get in touch with us.",
    service: "Services",
    branding: "Branding",
    design: "Design",
    marketing: "Marketing",
    advertisement: "Advertisement",
    company: "Company",
    about_us: "About Us",
    contact: "Contact",
    jobs: "Jobs",
    press_kit: "Press Kit",
    legal: "Legal",
    terms_of_use: "Terms of Use",
    privacy_policy: "Privacy Policy",
    cookie_policy: "Cookie Policy",
    company_info: "Apex Brat solution. Providing reliable tech since 2023",
    login: "Login",
    loginSentences:
      "If you already have a personal account, go to the login section.",
    username: "Username",
    password: "Password",
    login_button: "Login",
    success: "Login successful!",
    error: "Error! Please check your credentials.",
    registerSentences:
      "If you don't have a personal account, you can go to the registration page.",
    signUp: "Sign Up",
    hero: "Implement innovations and take your business to the next level. We ensure success through our technological solutions.",
    contact:
      "To get in touch, please fill out the form below or contact us directly via email.",
    contact_us: "Contact Us",
    contact:
      "To get in touch, please fill out the form below or contact us directly via email.",
    first_name: "First Name",
    first_name_placeholder: "Your First Name",
    last_name: "Last Name",
    last_name_placeholder: "Your Last Name",
    email: "Email",
    email_placeholder: "Your Email",
    message: "Message",
    message_placeholder: "Write your message here...",
    send_message: "Send Message",
    response_time: "We will respond to your message within 24 hours.",
    about_intro:
      "Our company is dedicated to providing the best experience in technological solutions and services to our clients. We aim to work based on innovation, high quality, and collaboration.",
    about_us_alt: "About Us",
    about_detail:
      "Our team consists of skilled professionals and strategists who offer innovative projects and solutions to our clients. Every project is a new achievement and opportunity for us.",
    service_1: "Innovative services",
    service_2: "High-quality technologies",
    service_3: "Customer trust and satisfaction",
  },
};

export default t;
