import Root from "./Components/Root";
import "./globals.css";

export const metadata = {
  title: "ApexBrat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <head>
        <link rel="icon" href="/favicon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={` antialiased h-[100vh] bg-white dark:bg-gray-900`}>
        <Root>{children}</Root>
      </body>
    </html>
  );
}
